services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - db
    networks:
      - sonar_net
    environment:
      SONAR_JDBC_URL: jdbc:sqlserver://db:1433;databaseName=sonar
      SONAR_JDBC_USERNAME: sa
      SONAR_JDBC_PASSWORD: P@sswOrd123
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: P@sswOrd123
    networks:
      - sonar_net
    volumes:
      - sonar_db:/var/opt/mssql
    ports:
      - "1433:1433"

networks:
  sonar_net:
    driver: bridge

volumes:
  sonar_data:
  sonar_logs:
  sonar_db:
